apiVersion: v1 # anyone with API access can retrieve or modify a Secret
kind: Secret
metadata:
  name: sensitive-secret
type: Opaque # base64 encoded secret data
data:
  username: YWRtaW4=  # base64 encoded value of 'admin' igual echo -n 'admin' | base64
  password: cGFzc3dvcmQxMjM=  # base64 encoded value of 'password123' igual echo -n 'password123' | base64

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: sensitive-secret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: sensitive-secret
            key: password